### ISSUE TITLE
unwind-protect

### ISSUE THREAD

**Issue by remexre** [fused-effects/fused-effects-resumable#4]
Would a PR for an `unwind-protect` equivalent be accepted, and it make sense to provide it here (rather than as a separate effect that the carriers defined here also provide)?

**Comment by robrix** [comment]
I don’t think I know enough about `unwind-protect` to be able to comment authoritatively; it looks something like `finally`, but I’m not sure that that captures it entirely. Could you describe it in a little more detail please?

Assuming that we can provide good semantics for it I don’t see any reason not to add it; its semantics, and particularly their laws, would guide whether we’d want to define it as part of the extant `Resumable` effect or make it a new effect (tho likely still part of this package, and provided by either or both of the carriers).

**Comment by remexre** [comment]
Oh, yeah, `finally` looks possibly equivalent, depending on exactly how exceptions work. CL conditions may not unwind (e.g. if the condition provides an "ignore this error" restart), in which case `unwind-protect` doesn't (yet) run.
